name: publish on tag

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        working-directory: packages/react-native-ultimate-config
      - run: npm publish
        working-directory: packages/react-native-ultimate-config
