name: test

on: push

jobs:
  test-ios-config:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies - lib
        run: yarn
      - name: install dependencies - example
        working-directory: example
        run: yarn
      - name: init env
        working-directory: example
        run: yarn rnuc .env.yaml
      - name: pods (ios only)
        working-directory: example/ios
        run: pod install
      # - name: print file
      #   working-directory: example
      #   run: cat node_modules/react-native-ultimate-config/ios/ConfigValues.h
      - name: install detox stuff
        run: |
          brew tap wix/brew
          brew install applesimutils
          npm install -g detox
      - name: build
        working-directory: example
        run: detox build --configuration ios.sim.release
      - name: Test if config has been injected
        working-directory: example/ios
        run: |
          /usr/libexec/PlistBuddy -c "Print :CFBundleDisplayName" build/Build/Products/Release-iphonesimulator/example.app/Info.plist 2>/dev/null | grep 'RNUC Demo'
      - name: e2e test
        working-directory: example
        run: detox test --configuration ios.sim.release

  test-android-config:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies - lib
        run: yarn
      - name: install dependencies - example
        run: |
          yarn
          cd android
          yarn rnuc .env.yaml
          ./gradlew assembleDebug
        working-directory: example
      - name: Test if config has been injected
        run: |
          grep 'public static final String APP_NAME = "RNUC Demo"' android/app/build/generated/source/buildConfig/debug/com/example/BuildConfig.java
          grep 'public static final String STRING_VALUE = "hello"' android/app/build/generated/source/buildConfig/debug/com/example/BuildConfig.java
          grep 'public static final boolean BOOLEAN_VALUE = false' android/app/build/generated/source/buildConfig/debug/com/example/BuildConfig.java
          grep 'public static final int NUMBER_VALUE = 42' android/app/build/generated/source/buildConfig/debug/com/example/BuildConfig.java

          xmllint --xpath '//resources/string[@name="APP_NAME"]'  android/app/build/generated/res/resValues/debug/values/gradleResValues.xml | grep "RNUC Demo"

          grep APP_NAME android/app/build/generated/not_namespaced_r_class_sources/debug/r/com/example/R.java
          grep STRING_VALUE android/app/build/generated/not_namespaced_r_class_sources/debug/r/com/example/R.java
          grep BOOLEAN_VALUE android/app/build/generated/not_namespaced_r_class_sources/debug/r/com/example/R.java
          grep NUMBER_VALUE android/app/build/generated/not_namespaced_r_class_sources/debug/r/com/example/R.java
        working-directory: example

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: yarn
      - run: yarn test
