name: test

on: push

jobs:
  test-ios-config:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        working-directory: example
        run: yarn
      - name: init env
        working-directory: example
        run: yarn setenv .env
      - name: pods (ios only)
        working-directory: example/ios
        run: pod install
      - name: build
        working-directory: example/ios
        run: xcodebuild -workspace example.xcworkspace -scheme example -sdk iphonesimulator13.2 -derivedDataPath build build
      - name: Test if config has been injected
        working-directory: example/ios
        run: |
          /usr/libexec/PlistBuddy -c "Print :CFBundleDisplayName" build/Build/Products/Debug-iphonesimulator/example.app/Info.plist 2>/dev/null | grep 'RNUC Demo'


  test-android-config:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          yarn
          cd android
          yarn setenv .env
          ./gradlew assembleDebug
        working-directory: example  
      - name: Test if config has been injected
        run: |
          grep 'public static final String APP_NAME = "RNUC Demo"' android/app/build/generated/source/buildConfig/debug/com/example/BuildConfig.java
          xmllint --xpath '//resources/string[@name="APP_NAME"]'  android/app/build/generated/res/resValues/debug/values/gradleResValues.xml | grep "RNUC Demo"
          grep APP_NAME android/app/build/generated/not_namespaced_r_class_sources/debug/r/com/example/R.java
        working-directory: example  
